version: '3.6'
services:

  kong-database:
    image: postgres:${POSTGRES_VERSION:-9.6}
    container_name: ${STACK_PREFIX:-kongstack}postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-kong}
      POSTGRES_DB: ${POSTGRES_DB:-kong}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  kong-prepare:
    image: kong:${KONG_VERSION:-latest}
    environment:
      KONG_DATABASE: postgres
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_USER: ${POSTGRES_USER:-kong}
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    restart: on-failure

  kong:
    image: kong:${KONG_VERSION:-latest}
    container_name: ${STACK_PREFIX:-kongstack}kong    
    environment:
      KONG_DATABASE: postgres
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: ${POSTGRES_DB:-kong}
      KONG_PG_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      KONG_PG_USER: ${POSTGRES_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "${KONG_HTTP_PORT:-8000}:8000"
      - "${KONG_HTTPS_PORT:-8000}:8443"
    depends_on:
      - kong-database
      - kong-prepare
  
  konga-prepare:
    image: pantsel/konga:${KONGA_VERSION:-next}
    command: "-c prepare -a postgres -u postgresql://${POSTGRES_USER:-kong}:${POSTGRES_PASSWORD:-kong}@kong-database:5432/${KONGA_DB}"
    restart: on-failure
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga:${KONGA_VERSION:-next}
    container_name: ${STACK_PREFIX:-kongstack}konga
    environment:
      NODE_ENV: ${KONGA_ENV:-production}
      TOKEN_SECRET: ${KONGA_TOKEN_SECRET}
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-kong}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      DB_DATABASE: ${KONGA_DB:-konga_db}
      DB_PG_SCHEMA: konga-schema      
    depends_on:
      - kong-database
      - kong
    ports:
      - "${KONGA_PORT:-1337}:1337"
    restart: always

networks:
  default:
    name: ${STACK_PREFIX:-kongstack}